title:       "Operating Systems 2021-1 (OS211)"
version:     "0028---30-Mar-2021"
copyright:   "2021-2021"
description: >- 
  OS 2021
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
author:           "Samuel Sharon"
address:          "1906400204"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://hans-sss.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/hans-sss/os211/"
urlghpage:        "https://hans-sss.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

